export const unblockTargets = [
  { slug: 'youtube', name: 'YouTube', category: 'Streaming', summary: 'Video platform blocked in some regions.' },
  { slug: 'twitter', name: 'Twitter/X', category: 'Social', summary: 'Social network restricted in certain countries.' },
  { slug: 'facebook', name: 'Facebook', category: 'Social', summary: 'Social network often blocked on school/work networks.' },
  { slug: 'instagram', name: 'Instagram', category: 'Social', summary: 'Photo-sharing platform with frequent geo-blocks.' },
  { slug: 'tiktok', name: 'TikTok', category: 'Social', summary: 'Short-form video service restricted in some regions.' },
  { slug: 'netflix', name: 'Netflix', category: 'Streaming', summary: 'Streaming catalog varies and is blocked in some regions.' },
  { slug: 'hulu', name: 'Hulu', category: 'Streaming', summary: 'Streaming service limited to specific countries.' },
  { slug: 'discord', name: 'Discord', category: 'Gaming', summary: 'Chat platform blocked on school/work networks.' },
  { slug: 'reddit', name: 'Reddit', category: 'Community', summary: 'Discussion platform blocked in some regions.' },
  { slug: 'telegram', name: 'Telegram', category: 'Messaging', summary: 'Messaging app restricted by some governments.' },
  { slug: 'whatsapp', name: 'WhatsApp', category: 'Messaging', summary: 'Messaging app blocked on some networks.' },
  { slug: 'snapchat', name: 'Snapchat', category: 'Social', summary: 'Social app often blocked on school networks.' },
  { slug: 'spotify', name: 'Spotify', category: 'Music', summary: 'Music streaming with regional limitations.' },
  { slug: 'twitch', name: 'Twitch', category: 'Streaming', summary: 'Streaming platform with geo-restrictions.' },
  { slug: 'roblox', name: 'Roblox', category: 'Gaming', summary: 'Gaming platform blocked at schools.' },
  { slug: 'steam', name: 'Steam', category: 'Gaming', summary: 'Game storefront restricted in some regions.' },
  { slug: 'chatgpt', name: 'ChatGPT', category: 'AI', summary: 'AI service blocked in some countries.' },
  { slug: 'wikipedia', name: 'Wikipedia', category: 'Education', summary: 'Information site censored in some regions.' },
  { slug: 'bbc-iplayer', name: 'BBC iPlayer', category: 'Streaming', summary: 'UK-only streaming service.' },
  { slug: 'signal', name: 'Signal', category: 'Messaging', summary: 'Secure messaging app blocked in some regions.' },
]
